business:
    type:     rest
    resource: WW\Gastro\ApiBundle\Controller\BusinessController
    name_prefix:  ge_api_

employee:
    type:     rest
    resource: WW\Gastro\ApiBundle\Controller\EmployeeController
    name_prefix:  ge_api_

worktime:
    type:     rest
    resource: WW\Gastro\ApiBundle\Controller\WorkTimeController
    parent:   employee
    name_prefix:  ge_api_

bill:
    type:     rest
    resource: WW\Gastro\ApiBundle\Controller\BillController
    parent:   employee
    name_prefix:  ge_api_

billorder:
    type:     rest
    resource: WW\Gastro\ApiBundle\Controller\BillOrderController
    parent:   bill
    name_prefix:  ge_api_

place:
    type:     rest
    resource: WW\Gastro\ApiBundle\Controller\PlaceController
    name_prefix:  ge_api_




