<?php

namespace WW\Gastro\ApiBundle\Entity;

/**
 * BusinessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessRepository extends \Doctrine\ORM\EntityRepository
{
}
